### ISSUE TITLE
Using KT17 on MacOS

### ISSUE THREAD

**Issue by liamtomosedwards** [mattkjames7/KT17#1]
Has anyone used this package on MacOS? I have installed _GCC_ and _make_ using Homebrew but it is still giving the error saying that libkt.so cannot be found. Any help would be hugely appreciated!

**Comment by mattkjames7** [comment]
Hi, I haven't yet ported this to MacOS, but it should be fairly doable to hack an existing installation into working...

If you navigate to where the package is installed in your env/global `site-packages` directory and find the C++ directory (`site-packages/KT17/__data/libkt`) you might be able to recompile it manually using `make`.

In some of the other packages I have ported, I have had to deal with a few minor quirks with Homebrew GCC, but it might just compile first time with a bit of luck!

I'll see if I can find the time to port it properly over the next week or so...

**Comment by liamtomosedwards** [comment]
Hi Matt,

I've tried recompiling it manually using `make` but to no avail, unfortunately. I might be doing it wrong (I'm not the most experienced with this!) but I would also massively appreciate if you could get it ported to MacOS. Thank you!

**Comment by mattkjames7** [comment]
Hi Liam,

I have created a new version (1.1.1) which should be available to install via `pip` - hopefully the changes I have made will mean that it works for you!

I have tested it myself on a VM instance of MacOS Big Sur, which I know is a bit dated, but it did at least run correctly on that.

Please let me know/close the issue if it does work, cheers!

**Comment by liamtomosedwards** [comment]
Hi Matt,

Version 1.1.1 has worked! Thank you so much!
